networks:
  default:

services:
  countryside:
    restart: unless-stopped
    build:
      context: .
    container_name: countryside
    image: vawz/countryside
    # set it to 0 if you are running as root
    # else find the right id with the id -u command
    #user: '0'
    user: ${USERID}
    ports:
      - "8080:8080"
    environment:
      # log info, debug, error....
      - RUST_LOG=${RNOSTR_LOG:-info}
    volumes:
      - $PWD/data:/app/data
      - $PWD/config:/app/config
